### ISSUE TITLE
Misconfiguration

### ISSUE THREAD

**Issue by creatzor** [graphaware/neo4j-noderank#14]
Noderank logs this every second `WARN  Relationship Inclusion Policy allows for a relationship, which leads to a node that is not included by the Node Inclusion Policy. This is likely a mis-configuration`

I dont understand what i'm doing wrong with the config, since it seems to be very minimal:

`##### config for users
#module id = NRUsers
com.graphaware.module.NRUsers.1=com.graphaware.module.noderank.NodeRankModuleBootstrapper
com.graphaware.module.NRUsers.maxTopRankNodes=10
com.graphaware.module.NRUsers.dampingFactor=0.85
com.graphaware.module.NRUsers.propertyKey=nr_users
com.graphaware.module.NRUsers.node=hasLabel('User') 
#com.graphaware.module.NRUsers.relationship=isType('LAST_POST') || isType('PREV') 
`

Any leads to a solution would be deeply appreciated as my log file i growing infinitely large.

**Comment by bachmanm** [comment]
It means that the module follows a relationship according to your specification (which is *any* relationship since your last config line is commented out). These relationships lead to nodes which are not `User`s. Hence the warning.

**Comment by creatzor** [comment]
@bachmanm I see, so multiple nodes (not just user) can be reached by the relationship i commented out, so even with it in place i believe i'd have the same issue. Is there a way for me to be even more specific? Where should I start? Can i make the relationships directional and chain some together?

:PREV is a part of many linked lists, :LAST_POST is applicable to 2 different types of nodes.

I was attempting to create a "trending" feature. Or am I misunderstanding the use of node-rank?

**Comment by bachmanm** [comment]
Could you describe your model in a little bit more detail, i.e. what links to what and how?

**Comment by creatzor** [comment]
So a user has a double linked list of posts, each post can have a double linked list of images.
:Page can have a double linked list of posts also.
:Page can have (:Page)-[:HAS_MEMBER]->(:User)
`(User)-[:LAST_POST]->(p1:Post)-[:PREV]->(p2:Post)-[:PREV]->(p3:Post)
(p1)<-[:NEXT]-(p2)<-[:NEXT]-(p3)

(p1)-[:LAST_IMAGE]->(im1:Image)-[:PREV]->(im2)
(im1)<-[:NEXT]-(im2)
`

**Comment by bachmanm** [comment]
First of all, I'd say your NEXT relationships don't need to be there at all, see http://graphaware.com/neo4j/2013/10/11/neo4j-bidirectional-relationships.html

I'm actually not sure that this a case for NodeRank (which effectively is an iterative version of PageRank). It's designed for websites/users/... linking with each other using directed relationships and finding the most "important" ones. I don't see how this can be applied here but I may be missing something..

**Comment by creatzor** [comment]
Thanks for the tip! We'll phase out that relationship. 

So it seems the solution here is to use a server extension or Reco.. While we make that transition, is there a way we can turn off the logging?
@bachmanm

**Comment by bachmanm** [comment]
which version are you on?

**Comment by creatzor** [comment]
3.0.6.43.3

**Comment by bachmanm** [comment]
Could you try to set the logging level of ` com.graphaware.module.noderank` to `ERROR`?

This should work: http://stackoverflow.com/questions/35011922/neo4j-graphaware-framework-logging-debugging
