### ISSUE TITLE
Memory issues when using NodeRank with Neo4J 2.2.2

### ISSUE THREAD

**Issue by sceee** [graphaware/neo4j-noderank#2]
Hi,

I am trying to use NodeRank with a small Neo4J database containing 2000 Nodes and 6000 Relationships. The database folder is fairly small (few MBs) after inserting all Nodes and Relationships but it increases steadily to over 12GB when I stopped it.
Is such big disk space consumption normal or is there a problem regarding a disk memory leak?

Could this be a problem with cyclic relationships (a->b->c->a or directly a->b->a) or multiple relationships from the same node with the same type (a->b and another few a->b)?

**Comment by bachmanm** [comment]
what does your neo4j.properties look like? Could you check what takes up the space? Most likely, it is going to be logs rather than the actual data in the database.

**Comment by sceee** [comment]
Thanks for the fast response.
There is a growing number of neostore.transaction.db.X files in the /var/lib/neo4j/data/graph.db/ directory. All of them have 250MB size and the last one is always increasing until there is a new one created when 250MB are reached.

My neo4j.properties is stock so there is nothing in there except the stock comments and of course the added NodeRank config:

``` com.graphaware.runtime.enabled=true

#NR becomes the module ID:
com.graphaware.module.NR.1=com.graphaware.module.noderank.NodeRankModuleBootstrapper

#optional number of top ranked nodes to remember, the default is 10
com.graphaware.module.NR.maxTopRankNodes=10000

#optional daming factor, which is a number p such that a random node will be selected at any step of the algorithm
#with the probability 1-p (as opposed to following a random relationship). The default is 0.85
com.graphaware.module.NR.dampingFactor=0.85

#optional key of the property that gets written to the ranked nodes, default is "nodeRank"
com.graphaware.module.NR.propertyKey=NodeRank

#optionally specify nodes to rank using an expression-based node inclusion policy, default is all business (i.e. non-framework-internal) nodes
com.graphaware.module.NR.node=hasLabel('MYLABEL')

#optionally specify relationships to follow using an expression-based relationship inclusion policy, default is all business (i.e. non-framework-internal) relationships
com.graphaware.module.NR.relationship=isType('MYREL')
```

**Comment by bachmanm** [comment]
This is Neo4j keeping logical logs, nothing to do with NodeRank (apart from the fact that it is continuously executing small transactions against the database, so the logs are growing). 

See here: http://neo4j.com/docs/stable/configuration-settings.html#config_keep_logical_logs

I'd try limiting the size of the logs in neo4j.properties, see also here: http://neo4j.com/docs/stable/configuration-logical-logs.html

**Comment by sceee** [comment]
Thank you very much for the fast help, I will try to limit the logical log size.

**Comment by bachmanm** [comment]
no worries

**Comment by tinwelint** [comment]
Know that log retention policy is enforced every checkpoint, where interval of checkpoints is controlled by two parameters:
- `dbms.checkpoint.interval.time` which defaults to 5 min
- `dbms.checkpoint.interval.tx` which defaults to 100 000 transactions

in between checkpoints transaction log sizes can be surpassed by any lengths. What's your checkpoint interval configuration?
