### ISSUE TITLE
[Solved] Multiple labels (node inclusion policy)

### ISSUE THREAD

**Issue by valkiii** [graphaware/neo4j-noderank#6]
Hello,
I am trying to run NodeRank on nodes which have different labels.
Which is the configuration I should use?
something like that:
com.graphaware.module.NR.node=hasLabel('Label1') OR hasLabel('Label2')
or
com.graphaware.module.NR.node=hasLabel('Label1' OR 'Label2')

 EDIT:
This is the one that works.
com.graphaware.module.NR.node=hasLabel('Label1') OR hasLabel('Label2')

**Comment by bachmanm** [comment]
or use `com.graphaware.module.NR.node=hasLabel('User') || hasLabel('Startup')`
