### ISSUE TITLE
Force a node to get pagerank

### ISSUE THREAD

**Issue by GeorgeL9** [graphaware/neo4j-noderank#7]
I have a roughly 8GB neo4j database, and leaving noderank to run overnight only got 5% of the nodes covered.

Is there a way to force noderank to run on a specific subset of the graph which hasn't been ranked yet, say I request a specific node, and want its neighbors noderank?

This is my server properties (excerpt):

org.neo4j.server.thirdparty_jaxrs_classes=com.graphaware.server=/graphaware
com.graphaware.runtime.timing.delay=1

com.graphaware.runtime.timing.maxDelay=1

com.graphaware.runtime.timing.minDelay=1

com.graphaware.runtime.timing.busyThreshold=100

com.graphaware.runtime.timing.maxSamples=200

com.graphaware.runtime.timing.maxTime=2000
com.graphaware.runtime.enabled=true

com.graphaware.module.NR.1=com.graphaware.module.noderank.NodeRankModuleBootstrapper
com.graphaware.module.NR.maxTopRankNodes=10

com.graphaware.module.NR.dampingFactor=0.001

com.graphaware.module.NR.propertyKey=nodeRank

**Comment by bachmanm** [comment]
Interesting - could you get in touch (info at graphaware dot com) to discuss? In short, there is no such option today but we're going to add one soon, along with normalising the values and a few other improvements around additions and deletions of nodes and relationships.

One thing I would say about your settings is that it's gonna take a very long time to actually converge to page rank with dampingFactor set to such a low value. What the "crawler" does with your setting is a random node selection in 99.9% of the cases, but it follows a relationships only in 0.01% of the cases.

**Comment by GeorgeL9** [comment]
Thanks Michael,
I will play around with the dampingFactor. I sent an email you provided.
