### ISSUE TITLE
make noderank run faster?

### ISSUE THREAD

**Issue by rotten** [graphaware/neo4j-noderank#8]
Is it possible to configure noderank to be more aggressive to get it to run a little faster?  I know it tries to "nice" itself and run in the background, but it is taking too long to converge.  (ie several days; when I need it to converge within hours)  [ Graph size:  About 2M nodes, 300M edges. Server size:  An AWS M4-2XL ]

**Comment by bachmanm** [comment]
You could try 

```
com.graphaware.runtime.timing.strategy=fixed
com.graphaware.runtime.timing.delay=1
```

which will use a thread at all times ignoring the load on the database. But it still only uses a single thread. If you wanted an aggressive one, you would use all threads, but you'd have to build that in yourself I'm afraid. Or use some sort of graph compute engine like GraphX over Spark

**Comment by rotten** [comment]
Thanks.  I'll give it a try.  

Max De Marzi has a pagerank api endpoint that runs through a fixed number of iterations fairly quickly - https://github.com/maxdemarzi/pagerank_spi - but it needs a lot of work to support inclusion policies and multiple property names.

I'd like to stick with Neo4j as my graph store (as opposed to moving to Giraph or TitanDB or something else). GraphX requires the graph to fit in memory (as near as I can tell) and my graph is now too big for that. (As does the python based graph-tool, networkx, and igraph.)   Maybe the new Mazerunner plugin that connects GraphX to Neo4j is the way to go - if it doesn't require oodles of memory to work.  I'll explore that more closely this week.

Noderank does exactly what I need, just not fast enough.

**Comment by rotten** [comment]
Setting those parameters appears to have driven the load average up a bit on my server (maybe by 50%?), but it also could be because the database is still warming up.  

I'm running three noderank values concurrently.  Does that mean I'm now running 3 threads?  Or are all three using the one thread?  I think all three might be sharing one thread because I only see one cpu being busy on my database server.  (the other 7 are idle)

I'm measuring convergence based on how many nodes have the noderank property yet and whether some of the nodes that I know are near the center are still changing.  Is there a better way?

**Comment by bachmanm** [comment]
They're still using a single thread. This is by design, because this is meant to run in the background. It would take us 2 days or so to add a feature where you could trigger the noderank computation on all available threads using REST API. Unfortunately, we don't have the time right now but this thread will stay here until we get around to doing this.

Re convergence, this is unfortunately hard to measure - the numbers will always be changing. All nodes having a nodeRank property greater than some small value should be a good measure for most graphs.
