### ISSUE TITLE
NodeRank calculated for every connected node despite hasLabel() setting

### ISSUE THREAD

**Issue by drgraduss** [graphaware/neo4j-noderank#9]
My NodeRank module configuration has setting below

`com.graphaware.module.NR.node=hasLabel('User')`

But node rank calculated for `:User` node and for every node connected to `:User` through one or more relationships.

Is it intended to behave like this?

**Comment by drgraduss** [comment]
Had a look at neo console.log found this warning:

```
Relationship Inclusion Policy allows for a relationship, which leads to a node that is not included by the Node Inclusion Policy. This is likely a mis-configuration
```

I haven't setup any relationship preferences in `com.graphaware.module.NR.relationship`

**Comment by drgraduss** [comment]
After I added `com.graphaware.module.NR.relationship=isType('SUBSCRIBED') || isType('KNOWS')` node rank calculated only on `:User` nodes which is fine.

Though I noticed that node rank never converges and monotonically increasing over time even on tiny sample graph. See below:

![Graph Example](https://raw.githubusercontent.com/drgraduss/misc/master/graph.png)

After running for 15 minutes you get:

```
UserId                                  Rank
----------------------------------------------
986f8fed-f048-4d27-bf46-1d0f83da0095    63340
67bbc38f-8fa3-46af-b312-caf38301bb6c    12021
7a978fce-ed71-4645-995f-2f5e7d01ed31    11950
bae1a8eb-6de5-4cba-9e93-5a94305cfa11    11939
3aeb686b-1187-4752-879b-2bf0d64ab52e    11799
69105ce8-fbc4-4728-9982-4b167ab93270    11703
1d8e9221-b067-4bdf-9b2e-f55889bdac33    11603
```

**UPDATE**

After night node rank still calculating.

```
UserId                                  Rank
----------------------------------------------
986f8fed-f048-4d27-bf46-1d0f83da0095    1013521
1d8e9221-b067-4bdf-9b2e-f55889bdac33    190025
67bbc38f-8fa3-46af-b312-caf38301bb6c    189985
7a978fce-ed71-4645-995f-2f5e7d01ed31    189885
3aeb686b-1187-4752-879b-2bf0d64ab52e    189538
69105ce8-fbc4-4728-9982-4b167ab93270    189405
bae1a8eb-6de5-4cba-9e93-5a94305cfa11    188636
```

Neo4j console.log is 1GB, because of node rank debug logs.

**Comment by bachmanm** [comment]
The number is ever-increasing, that's by design. Its absolute value has no meaning. It is the relative values that do. I agree this is sub-optimal, but we haven't gotten around to finding a good solution for normalising the values yet. Feel free to make a suggestion or, even better, submit a PR.

As for the logging, create a logback.xml file in your conf directory and add

```
<configuration>    
    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>%d{yyyy-MM-dd HH:mm:ss.SSSZ} %-5level %msg%n</pattern>
        </encoder>
    </appender>

    <logger name="com.graphaware" level="INFO"/>

    <root level="DEBUG">
        <appender-ref ref="STDOUT"/>
    </root>
</configuration>
```

This will set the framework logging level to INFO.

**Comment by drgraduss** [comment]
Thanks Michal!
